### ISSUE TITLE
"Change" column in all Markets table is not tracking price 

### ISSUE THREAD

**Issue by cmhchoi** [InjectiveLabs/injective-dex#351]
<img width="1172" alt="Screenshot 2021-11-07 at 3 36 12 PM" src="https://user-images.githubusercontent.com/9430957/140636952-c7db94d1-003a-44f5-b022-ad7a67370a73.png">

<img width="541" alt="Screenshot 2021-11-07 at 3 50 05 PM" src="https://user-images.githubusercontent.com/9430957/140636970-8f86ec06-aaff-45e3-83bf-490a5a77b6f4.png">

Seems to be tracking volume instead of price

**Comment by achilleas-kal** [comment]
I don't think there's anything wrong here.

1. Somebody sold 106 INJ at 4.348 and then the next move up was to 14 so the 222% change makes total sense.
2. The 0% change in other markets is understandable since there are no trades there.

![image](https://user-images.githubusercontent.com/83584143/140640317-92b7c7b5-199a-4512-ad7b-02297eaef545.png)

**Comment by cmhchoi** [comment]
Noted
