### ISSUE TITLE
Aggregated price levels - 0 price

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#402]
Hey @ThomasRalee, we should never see 0 as a price, the orders are so small and meaningless but they mess with the displayed data here which we somehow need to fix. I'm thinking that if we can't aggregated some price levels into the chosen unit i.e. 100 here we show them aggregated in the best possible unit below i.e. 10 or 1 and then 0.1.

Alternatively if the price level is less than 100 (or a given chosen unit) we just show 1 for all of them.

@cmhchoi can also advise.

![image](https://user-images.githubusercontent.com/83584143/142510921-ceb5d82a-a2d5-41a1-aea0-e66adbe113ef.png)

![image](https://user-images.githubusercontent.com/83584143/142510772-801f6b07-464b-476a-9753-0badd95a5967.png)

**Comment by cmhchoi** [comment]
I prefer to display as "<100", where 100 is the aggregation scale

So for example, if the 2nd diagram, the lowest would be "<100". If the user chooses scale as 10, then the lowest would be "<10"... When the user chooses the smallest scale, then we won't have this problem because the smallest scale should be able to show the smallest bid amount too
