### ISSUE TITLE
[Trades] Spot 100% Market Buy Order Error

### ISSUE THREAD

**Issue by shane-moore** [InjectiveLabs/injective-dex#536]
Selecting 100% as the Amount on the spot buy market order produces the error code below, which is returned by the INJ node via rpc.

Dividing the availableBalance by the required margin shown in the error message results in ~95%, which I assume is set up to allow for a 5% possible slippage.
![Screen Shot 2022-01-23 at 8 28 27 PM](https://user-images.githubusercontent.com/41407272/150717826-be42790b-4725-487c-b603-506d4b55c735.png)

I can think of at least a couple fixes:
a. Replace the user's option of 100% with 95% for market sell spot orders and ensure the `quantity` passed to `submitMarketOrder` in the `spot` store is 95% of the estimate.
b. Leave the UI still showing 100% but update the `quantity` passed to `submitMarketOrder` in the `spot` store to 95% of the estimated quantity

@bangjelkoski I can put together a PR for either a or b, unless you have other ideas, which are also welcome

**Comment by bangjelkoski** [comment]
Actually, that's not a proper solution because the UX is not good enough for the user. What happened here is that the user's quantity was calculated based on a `worstPrice` they can get based on the current orderbook state **without** applied slippage and during execution. However, the `executionPrice` on the chain happened with applied slippage because of the FBA model so it required more margin from the user than they actually have. 

We can update the UI to calculate everything with applied slippage but the problem is that if we do that most of the time it will be way off the `executionPrice` the user is going to get for his trade when proper liquidity is on the dex, resulting in wrongful information shown to the user.

**Comment by shane-moore** [comment]
Beautiful explanation. I got all that.

Constraints as I see them:
- the `Amount` requested by the user is set on the FE before the tx is broadcasted and doesn't account for slippage
- the 100% `worstPrice` based `Amount` tx is invalidated by the chain before being added to a block since potential slippage is taken into account
-  we don't know the clearing price until the FBA step during post-block validation
- The only useful parameters for this scenario that we can currently broadcast to `MsgBatchCreateSpotLimitOrders` are `price` and `quantity`, so the FBA is unaware of the address's `availableBalance`

@bangjelkoski are we able to modify the message sent to the chain? and add a request parameter for `availableBalance`?

Additional ideas:

c. create a hover over icon next to the 100% that states that the Amount for selecting 100% will vary due to slippage and liquidity fluctuations.  Then, we pass the `availableBalance` to the block and credit the user a base token amount =  (`avaliableBalance` - `fees`) / (`clearing price`)

d. work with order book algorythm team to create a floating margin calculation that is significantly less than 5% in times of high liquidity since the spread will be so low

e. do option b and add a hover over info icon that displays a note stating "Potential slippage and liquidity fluctuations could reduce the purchased quantity to ~95% of the displayed quantity.

Fun thought experiment so far!

**Comment by bangjelkoski** [comment]
> 

Correct, these are the constraints we have. For modifying the message we would have to do a chain upgrade, so that's not possible at the moment.

Adding a tooltip should be a small improvement of the UX, I agree, but it seems to me like a hack rather than a proper solution. The liquidity should constantly improve on the DEX, it's an ongoing effort, so hopefully, we can see fewer and fewer errors caused by the FBA applying slippage when matching the orders. 

Lets keep the discussion open until we can get some nice and elegant solution.

**Comment by shane-moore** [comment]
Yes, and prioritizing bridge creation will certainly aid in moving liquidity over to the dex, while opening up interesting opportunities for traders such as arbitrage.  It's a bright road ahead.

**Comment by bangjelkoski** [comment]
Resolved
