### ISSUE TITLE
BAYC/WETH PERP add (powered by NFT Bank)

### ISSUE THREAD

**Issue by ThomasRalee** [InjectiveLabs/injective-dex#692]
### Context:
Show the price feed provider for BAYC floor price - i.e. NFTBank. This is only applicable to BAYC/WETH PERP market.
- Given BAYC/WETH PERP is the latest listing, when it shows up as WHAT'S NEW highlighted pair, the users should see Powered by NFT Bank.
![image (1).png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/a48f420b-71f4-4286-b378-b7f2ba9290b9)
- When BAYC/WETH PERP is listed on Injective Pro, users should see Powered by NFT Bank for BAYC/WETH PERP market.
![image (2).png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/3986dc73-11a2-40a7-b2d1-d12e46f43fdb)
- Mobile viewport for BAYC/WETH PERP as the WHAT'S NEW highlighted pair.
![image (3).png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/b4f60660-57b6-4302-9d13-4e863685ee85)
- Mobile viewport for BAYC/WETH PERP in the list of markets.
![image (4).png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/a381c14d-23d4-48cd-8c8e-75b6273dc71e)

**Comment by terencetang9** [comment]
@ThomasRalee 

One small change wrt to the **Powered By** information.
We will show both Burnt Finance and NFT Bank logos.
If user hovers over the icon, the tooltip with the company name will show up and the icon will turn into colored version instead of greyscale.
Users can tap the icon to go to the corresponding website on a separate tab.
Burnt Finance: https://burnt.com/
NFT Bank: https://nftbank.ai/

**Comment by Tofel** [comment]
@terencetang9 I think we should prevent movement of the "Powered by" element when user hovers over it and it's displayed in coloured version. Currently there's a slight one.
