### ISSUE TITLE
Invalid transfer direction on transfer modal,

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#814]
**Describe the bug**
Invalid transfer direction on transfer modal, when transferring funds FROM trading account.

**To Reproduce**
1. Open portfolio.
2. Click on Trading Account panel.
3. Click "Transfer" on the top of the page.

**Expected behavior**
Transfer direction is Trading account -> Wallet, not Wallet -> Trading account.

**Screenshots**
![image](https://user-images.githubusercontent.com/20401585/169484424-f01d9cfa-7fa8-4de6-aad1-23472392a492.png)

**Comment by shane-moore** [comment]
i'm inquiring with @terencetang9 to get a feel for what is the expected behavior

**Comment by shane-moore** [comment]
notes from Slack convo as to why this ticket is being closed:
`Cool thanks! We don't have to fix this issue as the master [Transfer] button is at the top so the hierarchy is above everything else - we can keep the existing behaviour for now.
[1:31](https://injectivelabsinc.slack.com/archives/C03GWJUNUPQ/p1653561109125649)
Definitely need a clearer information architecture design for this - [@Ruth](https://injectivelabsinc.slack.com/team/U03G6QC2WTS) will help later since design resource has been pulled to focus on explorer side of things at the moment. (edited)`
